"use client";

import React, { useState, useRef, useEffect, Suspense } from "react";
import Link from "next/link";
import { useAuth } from "@/hooks/useAuth";
import { Opportunity } from "@/types";
import { OpportunityDetailModal } from "@/components/details/OpportunityDetailModal";
import { VerificationStatusBadge } from "@/components/common/VerificationStatusBadge";
import {
  Bot,
  User,
  Send,
  Sparkles,
  ShieldAlert,
  ExternalLink,
  BookOpen,
  ArrowRight,
  CheckCircle2,
  RefreshCw,
  AlertTriangle,
  FileCheck,
  Building,
  Info,
  Layers,
  GraduationCap,
  Calendar,
  Lock,
} from "lucide-react";

interface ChatMessage {
  id: string;
  sender: "user" | "assistant";
  text: string;
  timestamp: string;
  databaseOpportunities?: Opportunity[];
  documentChecklist?: {
    docName: string;
    docType: string;
    isMandatory: boolean;
    issuingAuthority?: string;
    schemeTitle: string;
  }[];
  officialSources?: {
    portalName: string;
    department: string;
    url: string;
    isGovernmentDomain: boolean;
  }[];
  verificationNotes?: string[];
  disclaimer?: string;
}

const SUGGESTED_QUESTIONS = [
  "What scholarships might apply to me?",
  "What documents do I need?",
  "What opportunities are available for college students?",
  "How can I search by state?",
  "What does this eligibility requirement mean?",
  "What is the application deadline?",
];

const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: "msg-welcome",
    sender: "assistant",
    text: "Namaste! I am your **OpportunityX AI Advisor**, strictly grounded in our verified scholarships and government schemes database.\n\nI can help you understand statutory eligibility rules, identify required documents, check official deadlines, and find opportunities tailored to your life stage and state.\n\n**Zero Hallucinations Guarantee**: I will never invent scholarships or guarantee eligibility. Feel free to ask a question below or click any of the suggested prompts!",
    timestamp: "Just now",
    databaseOpportunities: [],
    officialSources: [
      {
        portalName: "National Scholarship Portal (NSP)",
        department: "Ministry of Education & MeitY",
        url: "https://scholarships.gov.in",
        isGovernmentDomain: true,
      },
      {
        portalName: "myScheme Portal",
        department: "Government of India",
        url: "https://www.myscheme.gov.in",
        isGovernmentDomain: true,
      },
    ],
    verificationNotes: [
      "All answers are generated by cross-referencing published government scheme guidelines in our database.",
      "Final sanction depends on digital/physical document verification by the issuing authority.",
    ],
    disclaimer:
      "A Likely Match or AI recommendation does NOT constitute a guarantee of award or formal eligibility. Final determination rests with the issuing ministry/authority.",
  },
];

function AIAssistantChat() {
  const { user, profile, loginAsDemoPersona } = useAuth();

  const [messages, setMessages] = useState<ChatMessage[]>(INITIAL_MESSAGES);
  const [inputQuery, setInputQuery] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [selectedOpportunity, setSelectedOpportunity] = useState<Opportunity | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (queryText?: string) => {
    const textToSend = (queryText || inputQuery).trim();
    if (!textToSend || isLoading) return;

    const userMessageId = `user-${Date.now()}`;
    const userMsg: ChatMessage = {
      id: userMessageId,
      sender: "user",
      text: textToSend,
      timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMsg]);
    if (!queryText) setInputQuery("");
    setIsLoading(true);

    try {
      // Secure server-side call: no API keys exposed client-side
      const res = await fetch("/api/ai-assistant", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: textToSend,
          userProfile: profile || null,
        }),
      });

      const data = await res.json();

      if (data.success) {
        const assistantMsg: ChatMessage = {
          id: `bot-${Date.now()}`,
          sender: "assistant",
          text: data.reply,
          timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
          databaseOpportunities: data.databaseOpportunities || [],
          documentChecklist: data.documentChecklist || [],
          officialSources: data.officialSources || [],
          verificationNotes: data.verificationNotes || [],
          disclaimer: data.disclaimer,
        };
        setMessages((prev) => [...prev, assistantMsg]);
      } else {
        throw new Error(data.error || "Failed to fetch response");
      }
    } catch (err: any) {
      const errorMsg: ChatMessage = {
        id: `bot-err-${Date.now()}`,
        sender: "assistant",
        text: `⚠️ **Connection Notice:** Unable to reach the assistant server (${err.message}). Please verify your network connection and try again.`,
        timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        databaseOpportunities: [],
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleClear = () => {
    setMessages(INITIAL_MESSAGES);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 pb-24 lg:pb-12 space-y-6">
      {/* ─────────────────────────────────────────────────────────────
          1. HEADER & ZERO-HALLUCINATION TRUST BANNER
          ───────────────────────────────────────────────────────────── */}
      <div>
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-brand-50 text-brand-800 text-xs font-bold mb-2 border border-brand-200 shadow-2xs">
          <Bot className="w-4 h-4 text-brand-600" />
          <span>Grounded in Official Schemes Database • Zero Hallucinations</span>
        </div>
        <h1 className="text-2xl sm:text-4xl font-black text-slate-900 tracking-tight">
          OpportunityX AI Advisor
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 mt-1 max-w-2xl leading-relaxed">
          Ask questions regarding statutory eligibility, application documents, state quotas, or deadlines. The advisor explains authentic database records without inventing unverified schemes.
        </p>
      </div>

      {/* Profile Context Bar & Demo Personas */}
      <div className="p-4 rounded-2xl bg-white border border-slate-200 shadow-2xs flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-brand-50 text-brand-700 flex items-center justify-center font-bold">
            <User className="w-4 h-4" />
          </div>
          <div>
            <span className="text-[11px] font-semibold text-slate-500 block">
              Active Evaluation Profile:
            </span>
            <span className="font-bold text-slate-900">
              {profile ? `${profile.name} (${profile.state} • ${profile.category} • ${profile.lifeStage})` : "Guest (General Guidance Mode)"}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-[11px] font-semibold text-slate-500 hidden sm:inline">
            Quick Personas:
          </span>
          <button
            type="button"
            onClick={() => loginAsDemoPersona("student")}
            className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-slate-50 hover:bg-slate-100 border border-slate-200 cursor-pointer"
          >
            🎓 Pooja (Student)
          </button>
          <button
            type="button"
            onClick={() => loginAsDemoPersona("farmer")}
            className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-slate-50 hover:bg-slate-100 border border-slate-200 cursor-pointer"
          >
            🌾 Ramesh (Farmer)
          </button>
          <button
            type="button"
            onClick={() => loginAsDemoPersona("entrepreneur")}
            className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-slate-50 hover:bg-slate-100 border border-slate-200 cursor-pointer"
          >
            💼 Lakshmi (Entrepreneur)
          </button>
        </div>
      </div>

      {/* ─────────────────────────────────────────────────────────────
          2. SUGGESTED QUESTIONS (PROMPT CHIPS)
          ───────────────────────────────────────────────────────────── */}
      <div className="space-y-2">
        <span className="text-xs font-bold text-slate-600 uppercase tracking-wider flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5 text-brand-600" />
          <span>Frequently Asked Questions (Click to Ask):</span>
        </span>
        <div className="flex flex-wrap gap-2">
          {SUGGESTED_QUESTIONS.map((q, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => handleSend(q)}
              disabled={isLoading}
              className="px-3 py-1.5 rounded-xl text-xs font-semibold bg-white hover:bg-brand-50 text-slate-700 hover:text-brand-800 border border-slate-200 hover:border-brand-300 transition-all text-left shadow-2xs disabled:opacity-50 cursor-pointer"
            >
              💬 {q}
            </button>
          ))}
        </div>
      </div>

      {/* ─────────────────────────────────────────────────────────────
          3. MAIN CHAT CONVERSATION WINDOW
          ───────────────────────────────────────────────────────────── */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden flex flex-col h-[520px] sm:h-[620px]">
        {/* Chat Messages Stream */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-6">
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex gap-3 max-w-4xl ${
                msg.sender === "user" ? "ml-auto flex-row-reverse" : "mr-auto"
              }`}
            >
              {/* Avatar */}
              <div
                className={`w-9 h-9 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-2xs ${
                  msg.sender === "user"
                    ? "bg-brand-600 text-white"
                    : "bg-gradient-to-tr from-brand-900 to-indigo-900 text-white"
                }`}
              >
                {msg.sender === "user" ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
              </div>

              {/* Message Content */}
              <div className="space-y-3 max-w-2xl text-xs">
                {/* Bubble */}
                <div
                  className={`p-4 rounded-3xl ${
                    msg.sender === "user"
                      ? "bg-brand-600 text-white rounded-tr-xs"
                      : "bg-slate-50 border border-slate-200 text-slate-800 rounded-tl-xs space-y-3"
                  }`}
                >
                  <div className="whitespace-pre-line leading-relaxed text-xs sm:text-[13px]">
                    {msg.text}
                  </div>

                  {/* ── SECTION A: VERIFIED DATABASE RECORDS ── */}
                  {msg.databaseOpportunities && msg.databaseOpportunities.length > 0 && (
                    <div className="pt-2 border-t border-slate-200/80 space-y-2.5">
                      <div className="flex items-center justify-between">
                        <span className="font-black text-slate-900 text-xs flex items-center gap-1.5 uppercase tracking-wider">
                          <BookOpen className="w-3.5 h-3.5 text-brand-600" />
                          <span>Verified Database Records ({msg.databaseOpportunities.length}):</span>
                        </span>
                        <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold">
                          Official Sources
                        </span>
                      </div>

                      <div className="grid grid-cols-1 gap-2.5">
                        {msg.databaseOpportunities.map((opp) => (
                          <div
                            key={opp.id}
                            className="p-3.5 rounded-2xl bg-white border border-slate-200 hover:border-brand-400 transition-all shadow-2xs space-y-2 text-xs"
                          >
                            <div className="flex items-start justify-between gap-2">
                              <div>
                                <div className="flex items-center gap-1.5 flex-wrap">
                                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-700">
                                    {opp.type === "scholarship" ? "Scholarship" : "Scheme"}
                                  </span>
                                  <VerificationStatusBadge
                                    status={opp.verificationStatus}
                                    size="sm"
                                  />
                                </div>
                                <h4 className="font-extrabold text-slate-900 text-xs sm:text-sm mt-1">
                                  {opp.title}
                                </h4>
                                <p className="text-[11px] text-slate-500">
                                  {opp.provider}
                                </p>
                              </div>

                              <span className="font-black text-brand-700 whitespace-nowrap bg-brand-50 px-2 py-1 rounded-lg text-xs">
                                {opp.amount}
                              </span>
                            </div>

                            <p className="text-slate-600 text-[11px] line-clamp-2">
                              {opp.benefits}
                            </p>

                            <div className="flex items-center justify-between pt-1 border-t border-slate-100 text-[11px]">
                              <span className="text-slate-500 font-medium flex items-center gap-1">
                                <Calendar className="w-3 h-3 text-slate-400" />
                                <span>{opp.deadlineDate ? `Deadline: ${opp.deadlineDate}` : "Year-Round"}</span>
                              </span>

                              <div className="flex items-center gap-2">
                                <button
                                  type="button"
                                  onClick={() => setSelectedOpportunity(opp)}
                                  className="text-brand-600 font-bold hover:underline cursor-pointer"
                                >
                                  View Details
                                </button>
                                <a
                                  href={opp.officialWebsite}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="text-brand-600 hover:text-brand-700 font-bold inline-flex items-center gap-0.5"
                                >
                                  <span>Official Portal</span>
                                  <ExternalLink className="w-3 h-3" />
                                </a>
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* ── SECTION B: DOCUMENT CHECKLIST ── */}
                  {msg.documentChecklist && msg.documentChecklist.length > 0 && (
                    <div className="pt-2 border-t border-slate-200/80 space-y-1.5">
                      <span className="font-bold text-slate-800 text-[11px] uppercase tracking-wider flex items-center gap-1">
                        <FileCheck className="w-3.5 h-3.5 text-amber-600" />
                        <span>Required Compliance Documents:</span>
                      </span>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 text-[11px]">
                        {msg.documentChecklist.slice(0, 4).map((doc, idx) => (
                          <div key={idx} className="p-2 rounded-xl bg-white border border-slate-200 flex items-start gap-1.5">
                            <span className="text-brand-600 font-bold">✓</span>
                            <div>
                              <p className="font-bold text-slate-800">{doc.docName}</p>
                              {doc.issuingAuthority && (
                                <p className="text-[10px] text-slate-500">Issued by: {doc.issuingAuthority}</p>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* ── SECTION C: OFFICIAL SOURCES ── */}
                  {msg.officialSources && msg.officialSources.length > 0 && (
                    <div className="pt-2 border-t border-slate-200/80 flex items-center justify-between flex-wrap gap-2 text-[11px]">
                      <span className="font-bold text-slate-600">Official Portals:</span>
                      <div className="flex items-center gap-2 flex-wrap">
                        {msg.officialSources.map((src, idx) => (
                          <a
                            key={idx}
                            href={src.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="px-2 py-0.5 rounded-md bg-white border border-slate-200 text-brand-700 font-bold hover:bg-slate-50 inline-flex items-center gap-1"
                          >
                            <span>{src.portalName}</span>
                            <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* ── SECTION D: MANDATORY DISCLAIMER ── */}
                  {msg.disclaimer && (
                    <div className="p-2 rounded-xl bg-slate-100/80 border border-slate-200 text-[10px] text-slate-600 flex items-start gap-1.5">
                      <Info className="w-3 h-3 text-slate-400 flex-shrink-0 mt-0.5" />
                      <span>{msg.disclaimer}</span>
                    </div>
                  )}
                </div>

                <div className="text-[10px] text-slate-400 px-1">
                  {msg.timestamp}
                </div>
              </div>
            </div>
          ))}

          {/* Typing Indicator */}
          {isLoading && (
            <div className="flex gap-3 max-w-md">
              <div className="w-9 h-9 rounded-2xl bg-gradient-to-tr from-brand-900 to-indigo-900 text-white flex items-center justify-center flex-shrink-0">
                <Bot className="w-4 h-4 animate-pulse" />
              </div>
              <div className="p-4 rounded-3xl bg-slate-50 border border-slate-200 text-slate-600 text-xs flex items-center gap-2">
                <RefreshCw className="w-3.5 h-3.5 animate-spin text-brand-600" />
                <span>Searching verified database records and guidelines...</span>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Bar */}
        <div className="p-4 border-t border-slate-200 bg-slate-50/70">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              value={inputQuery}
              onChange={(e) => setInputQuery(e.target.value)}
              placeholder="Ask anything (e.g. 'What documents do I need for Pragati?', 'Karnataka scholarships for farmers')..."
              className="flex-1 px-4 py-3 text-xs sm:text-sm rounded-2xl bg-white border border-slate-200 text-slate-800 placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-brand-500 shadow-2xs"
            />
            <button
              type="submit"
              disabled={isLoading || !inputQuery.trim()}
              className="px-5 py-3 rounded-2xl bg-brand-600 hover:bg-brand-700 text-white font-bold text-xs sm:text-sm transition-all shadow-xs flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
            >
              <span>Send</span>
              <Send className="w-3.5 h-3.5" />
            </button>
          </form>

          <div className="flex items-center justify-between text-[11px] text-slate-400 pt-2 px-1">
            <span>OpportunityX-AI Assistant does not invent scholarships or store sensitive credentials.</span>
            <button
              type="button"
              onClick={handleClear}
              className="text-slate-500 hover:text-slate-700 hover:underline"
            >
              Reset Chat
            </button>
          </div>
        </div>
      </div>

      {/* ─────────────────────────────────────────────────────────────
          4. COMPREHENSIVE 8-SECTION OPPORTUNITY DETAIL MODAL
          ───────────────────────────────────────────────────────────── */}
      <OpportunityDetailModal
        opportunity={selectedOpportunity}
        onClose={() => setSelectedOpportunity(null)}
        isSaved={false}
      />
    </div>
  );
}

export default function AIAssistantPage() {
  return (
    <Suspense fallback={<div className="p-12 text-center text-slate-500">Loading AI Assistant...</div>}>
      <AIAssistantChat />
    </Suspense>
  );
}
